import { ThemeProvider } from '@/components/theme/theme-provider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const appleGaramond = localFont({
  src: [
    {
      path: './fonts/AppleGaramond.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/AppleGaramond-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/AppleGaramond-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-apple-garamond',
  display: 'swap',
});

const arialNarrow = localFont({
  src: './fonts/ArialNarrow.woff2',
  variable: '--font-arial-narrow',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${appleGaramond.variable} ${arialNarrow.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
